<?xml version="1.0" encoding="UTF-8" ?>
<Package name="mood-mirror" format_version="4">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions>
        <BehaviorDescription name="behavior" src="." xar="behavior.xar" />
    </BehaviorDescriptions>
    <Dialogs>
        <Dialog name="Emotes" src="Emotes/Emotes.dlg" />
        <Dialog name="Exit" src="Exit/Exit.dlg" />
    </Dialogs>
    <Resources>
        <File name="icon" src="icon.png" />
        <File name="laugh2" src="laugh2.wav" />
        <File name="runbrowser" src="runbrowser.py" />
        <File name="runserver" src="runserver.py" />
        <File name="index" src="html/index.html" />
        <File name="angular-slider" src="html/css/angular-slider.css" />
        <File name="app_menu" src="html/css/app_menu.css" />
        <File name="app_wizard" src="html/css/app_wizard.css" />
        <File name="dropdown" src="html/css/dropdown.css" />
        <File name="font" src="html/css/font.css" />
        <File name="modal" src="html/css/modal.css" />
        <File name="perfect-scrollbar" src="html/css/perfect-scrollbar.css" />
        <File name="din_blackalternate-webfont" src="html/css/FontFace/DIN_WOFF/din_blackalternate-webfont.eot" />
        <File name="din_blackalternate-webfont" src="html/css/FontFace/DIN_WOFF/din_blackalternate-webfont.svg" />
        <File name="din_blackalternate-webfont" src="html/css/FontFace/DIN_WOFF/din_blackalternate-webfont.ttf" />
        <File name="din_blackalternate-webfont" src="html/css/FontFace/DIN_WOFF/din_blackalternate-webfont.woff" />
        <File name="din_blackt-webfont" src="html/css/FontFace/DIN_WOFF/din_blackt-webfont.eot" />
        <File name="din_blackt-webfont" src="html/css/FontFace/DIN_WOFF/din_blackt-webfont.svg" />
        <File name="din_blackt-webfont" src="html/css/FontFace/DIN_WOFF/din_blackt-webfont.ttf" />
        <File name="din_blackt-webfont" src="html/css/FontFace/DIN_WOFF/din_blackt-webfont.woff" />
        <File name="din_bold-webfont" src="html/css/FontFace/DIN_WOFF/din_bold-webfont.eot" />
        <File name="din_bold-webfont" src="html/css/FontFace/DIN_WOFF/din_bold-webfont.svg" />
        <File name="din_bold-webfont" src="html/css/FontFace/DIN_WOFF/din_bold-webfont.ttf" />
        <File name="din_bold-webfont" src="html/css/FontFace/DIN_WOFF/din_bold-webfont.woff" />
        <File name="din_light-webfont" src="html/css/FontFace/DIN_WOFF/din_light-webfont.eot" />
        <File name="din_light-webfont" src="html/css/FontFace/DIN_WOFF/din_light-webfont.svg" />
        <File name="din_light-webfont" src="html/css/FontFace/DIN_WOFF/din_light-webfont.ttf" />
        <File name="din_light-webfont" src="html/css/FontFace/DIN_WOFF/din_light-webfont.woff" />
        <File name="din_lightalternate-webfont" src="html/css/FontFace/DIN_WOFF/din_lightalternate-webfont.eot" />
        <File name="din_lightalternate-webfont" src="html/css/FontFace/DIN_WOFF/din_lightalternate-webfont.svg" />
        <File name="din_lightalternate-webfont" src="html/css/FontFace/DIN_WOFF/din_lightalternate-webfont.ttf" />
        <File name="din_lightalternate-webfont" src="html/css/FontFace/DIN_WOFF/din_lightalternate-webfont.woff" />
        <File name="din_regular-webfont" src="html/css/FontFace/DIN_WOFF/din_regular-webfont.eot" />
        <File name="din_regular-webfont" src="html/css/FontFace/DIN_WOFF/din_regular-webfont.svg" />
        <File name="din_regular-webfont" src="html/css/FontFace/DIN_WOFF/din_regular-webfont.ttf" />
        <File name="din_regular-webfont" src="html/css/FontFace/DIN_WOFF/din_regular-webfont.woff" />
        <File name="ajax-loader" src="html/img/ajax-loader.gif" />
        <File name="happy" src="html/img/happy.png" />
        <File name="load-100px" src="html/img/load-100px.gif" />
        <File name="load-120px" src="html/img/load-120px.gif" />
        <File name="neutral" src="html/img/neutral.png" />
        <File name="question" src="html/img/question.png" />
        <File name="sad" src="html/img/sad.png" />
        <File name="adjust" src="html/js/adjust.js" />
        <File name="app" src="html/js/app.js" />
        <File name="bootstrap" src="html/js/bootstrap.js" />
        <File name="main" src="html/js/main.js" />
        <File name="routes" src="html/js/routes.js" />
        <File name="smoothie" src="html/js/smoothie.js" />
        <File name="index" src="html/js/controllers/index.js" />
        <File name="module" src="html/js/controllers/module.js" />
        <File name="mySampleController" src="html/js/controllers/mySampleController.js" />
        <File name="directives" src="html/js/directives/directives.js" />
        <File name="index" src="html/js/directives/index.js" />
        <File name="module" src="html/js/directives/module.js" />
        <File name="filters" src="html/js/filters/filters.js" />
        <File name="index" src="html/js/filters/index.js" />
        <File name="module" src="html/js/filters/module.js" />
        <File name="emileTestService" src="html/js/services/emileTestService.js" />
        <File name="index" src="html/js/services/index.js" />
        <File name="module" src="html/js/services/module.js" />
        <File name="prefService" src="html/js/services/prefService.js" />
        <File name="qimessagingService" src="html/js/services/qimessagingService.js" />
        <File name="videoService" src="html/js/services/videoService.js" />
        <File name="Chinese" src="html/languages/Chinese.json" />
        <File name="English" src="html/languages/English.json" />
        <File name="eula-English" src="html/languages/eula-English.html" />
        <File name="eula-Japanese" src="html/languages/eula-Japanese.html" />
        <File name="French" src="html/languages/French.json" />
        <File name="Japanese" src="html/languages/Japanese.json" />
        <File name="angular-ui-router" src="html/lib/angular-ui-router.js" />
        <File name="domReady" src="html/lib/domReady.js" />
        <File name="jquery.min" src="html/lib/jquery.min.js" />
        <File name="require" src="html/lib/require.js" />
        <File name="angular-animate" src="html/lib/angular/angular-animate.js" />
        <File name="angular-animate.min" src="html/lib/angular/angular-animate.min.js" />
        <File name="angular-animate.min.js" src="html/lib/angular/angular-animate.min.js.map" />
        <File name="angular-cookies" src="html/lib/angular/angular-cookies.js" />
        <File name="angular-cookies.min" src="html/lib/angular/angular-cookies.min.js" />
        <File name="angular-cookies.min.js" src="html/lib/angular/angular-cookies.min.js.map" />
        <File name="angular-csp" src="html/lib/angular/angular-csp.css" />
        <File name="angular-loader" src="html/lib/angular/angular-loader.js" />
        <File name="angular-loader.min" src="html/lib/angular/angular-loader.min.js" />
        <File name="angular-loader.min.js" src="html/lib/angular/angular-loader.min.js.map" />
        <File name="angular-resource" src="html/lib/angular/angular-resource.js" />
        <File name="angular-resource.min" src="html/lib/angular/angular-resource.min.js" />
        <File name="angular-resource.min.js" src="html/lib/angular/angular-resource.min.js.map" />
        <File name="angular-route" src="html/lib/angular/angular-route.js" />
        <File name="angular-route.min" src="html/lib/angular/angular-route.min.js" />
        <File name="angular-route.min.js" src="html/lib/angular/angular-route.min.js.map" />
        <File name="angular-sanitize" src="html/lib/angular/angular-sanitize.js" />
        <File name="angular-sanitize.min" src="html/lib/angular/angular-sanitize.min.js" />
        <File name="angular-sanitize.min.js" src="html/lib/angular/angular-sanitize.min.js.map" />
        <File name="angular-scenario" src="html/lib/angular/angular-scenario.js" />
        <File name="angular-touch" src="html/lib/angular/angular-touch.js" />
        <File name="angular-touch.min" src="html/lib/angular/angular-touch.min.js" />
        <File name="angular-touch.min.js" src="html/lib/angular/angular-touch.min.js.map" />
        <File name="angular" src="html/lib/angular/angular.js" />
        <File name="angular.min" src="html/lib/angular/angular.min.js" />
        <File name="angular.min.js" src="html/lib/angular/angular.min.js.gzip" />
        <File name="angular.min.js" src="html/lib/angular/angular.min.js.map" />
        <File name="errors" src="html/lib/angular/errors.json" />
        <File name="version" src="html/lib/angular/version.json" />
        <File name="version" src="html/lib/angular/version.txt" />
        <File name="angular-locale_af-na" src="html/lib/angular/i18n/angular-locale_af-na.js" />
        <File name="angular-locale_af-za" src="html/lib/angular/i18n/angular-locale_af-za.js" />
        <File name="angular-locale_af" src="html/lib/angular/i18n/angular-locale_af.js" />
        <File name="angular-locale_am-et" src="html/lib/angular/i18n/angular-locale_am-et.js" />
        <File name="angular-locale_am" src="html/lib/angular/i18n/angular-locale_am.js" />
        <File name="angular-locale_ar-001" src="html/lib/angular/i18n/angular-locale_ar-001.js" />
        <File name="angular-locale_ar-ae" src="html/lib/angular/i18n/angular-locale_ar-ae.js" />
        <File name="angular-locale_ar-bh" src="html/lib/angular/i18n/angular-locale_ar-bh.js" />
        <File name="angular-locale_ar-dz" src="html/lib/angular/i18n/angular-locale_ar-dz.js" />
        <File name="angular-locale_ar-eg" src="html/lib/angular/i18n/angular-locale_ar-eg.js" />
        <File name="angular-locale_ar-iq" src="html/lib/angular/i18n/angular-locale_ar-iq.js" />
        <File name="angular-locale_ar-jo" src="html/lib/angular/i18n/angular-locale_ar-jo.js" />
        <File name="angular-locale_ar-kw" src="html/lib/angular/i18n/angular-locale_ar-kw.js" />
        <File name="angular-locale_ar-lb" src="html/lib/angular/i18n/angular-locale_ar-lb.js" />
        <File name="angular-locale_ar-ly" src="html/lib/angular/i18n/angular-locale_ar-ly.js" />
        <File name="angular-locale_ar-ma" src="html/lib/angular/i18n/angular-locale_ar-ma.js" />
        <File name="angular-locale_ar-om" src="html/lib/angular/i18n/angular-locale_ar-om.js" />
        <File name="angular-locale_ar-qa" src="html/lib/angular/i18n/angular-locale_ar-qa.js" />
        <File name="angular-locale_ar-sa" src="html/lib/angular/i18n/angular-locale_ar-sa.js" />
        <File name="angular-locale_ar-sd" src="html/lib/angular/i18n/angular-locale_ar-sd.js" />
        <File name="angular-locale_ar-sy" src="html/lib/angular/i18n/angular-locale_ar-sy.js" />
        <File name="angular-locale_ar-tn" src="html/lib/angular/i18n/angular-locale_ar-tn.js" />
        <File name="angular-locale_ar-ye" src="html/lib/angular/i18n/angular-locale_ar-ye.js" />
        <File name="angular-locale_ar" src="html/lib/angular/i18n/angular-locale_ar.js" />
        <File name="angular-locale_bg-bg" src="html/lib/angular/i18n/angular-locale_bg-bg.js" />
        <File name="angular-locale_bg" src="html/lib/angular/i18n/angular-locale_bg.js" />
        <File name="angular-locale_bn-bd" src="html/lib/angular/i18n/angular-locale_bn-bd.js" />
        <File name="angular-locale_bn-in" src="html/lib/angular/i18n/angular-locale_bn-in.js" />
        <File name="angular-locale_bn" src="html/lib/angular/i18n/angular-locale_bn.js" />
        <File name="angular-locale_ca-ad" src="html/lib/angular/i18n/angular-locale_ca-ad.js" />
        <File name="angular-locale_ca-es" src="html/lib/angular/i18n/angular-locale_ca-es.js" />
        <File name="angular-locale_ca" src="html/lib/angular/i18n/angular-locale_ca.js" />
        <File name="angular-locale_cs-cz" src="html/lib/angular/i18n/angular-locale_cs-cz.js" />
        <File name="angular-locale_cs" src="html/lib/angular/i18n/angular-locale_cs.js" />
        <File name="angular-locale_da-dk" src="html/lib/angular/i18n/angular-locale_da-dk.js" />
        <File name="angular-locale_da" src="html/lib/angular/i18n/angular-locale_da.js" />
        <File name="angular-locale_de-at" src="html/lib/angular/i18n/angular-locale_de-at.js" />
        <File name="angular-locale_de-be" src="html/lib/angular/i18n/angular-locale_de-be.js" />
        <File name="angular-locale_de-ch" src="html/lib/angular/i18n/angular-locale_de-ch.js" />
        <File name="angular-locale_de-de" src="html/lib/angular/i18n/angular-locale_de-de.js" />
        <File name="angular-locale_de-li" src="html/lib/angular/i18n/angular-locale_de-li.js" />
        <File name="angular-locale_de-lu" src="html/lib/angular/i18n/angular-locale_de-lu.js" />
        <File name="angular-locale_de" src="html/lib/angular/i18n/angular-locale_de.js" />
        <File name="angular-locale_el-cy" src="html/lib/angular/i18n/angular-locale_el-cy.js" />
        <File name="angular-locale_el-gr" src="html/lib/angular/i18n/angular-locale_el-gr.js" />
        <File name="angular-locale_el" src="html/lib/angular/i18n/angular-locale_el.js" />
        <File name="angular-locale_en-as" src="html/lib/angular/i18n/angular-locale_en-as.js" />
        <File name="angular-locale_en-au" src="html/lib/angular/i18n/angular-locale_en-au.js" />
        <File name="angular-locale_en-bb" src="html/lib/angular/i18n/angular-locale_en-bb.js" />
        <File name="angular-locale_en-be" src="html/lib/angular/i18n/angular-locale_en-be.js" />
        <File name="angular-locale_en-bm" src="html/lib/angular/i18n/angular-locale_en-bm.js" />
        <File name="angular-locale_en-bw" src="html/lib/angular/i18n/angular-locale_en-bw.js" />
        <File name="angular-locale_en-bz" src="html/lib/angular/i18n/angular-locale_en-bz.js" />
        <File name="angular-locale_en-ca" src="html/lib/angular/i18n/angular-locale_en-ca.js" />
        <File name="angular-locale_en-dsrt-us" src="html/lib/angular/i18n/angular-locale_en-dsrt-us.js" />
        <File name="angular-locale_en-dsrt" src="html/lib/angular/i18n/angular-locale_en-dsrt.js" />
        <File name="angular-locale_en-fm" src="html/lib/angular/i18n/angular-locale_en-fm.js" />
        <File name="angular-locale_en-gb" src="html/lib/angular/i18n/angular-locale_en-gb.js" />
        <File name="angular-locale_en-gu" src="html/lib/angular/i18n/angular-locale_en-gu.js" />
        <File name="angular-locale_en-gy" src="html/lib/angular/i18n/angular-locale_en-gy.js" />
        <File name="angular-locale_en-hk" src="html/lib/angular/i18n/angular-locale_en-hk.js" />
        <File name="angular-locale_en-ie" src="html/lib/angular/i18n/angular-locale_en-ie.js" />
        <File name="angular-locale_en-in" src="html/lib/angular/i18n/angular-locale_en-in.js" />
        <File name="angular-locale_en-iso" src="html/lib/angular/i18n/angular-locale_en-iso.js" />
        <File name="angular-locale_en-jm" src="html/lib/angular/i18n/angular-locale_en-jm.js" />
        <File name="angular-locale_en-mh" src="html/lib/angular/i18n/angular-locale_en-mh.js" />
        <File name="angular-locale_en-mp" src="html/lib/angular/i18n/angular-locale_en-mp.js" />
        <File name="angular-locale_en-mt" src="html/lib/angular/i18n/angular-locale_en-mt.js" />
        <File name="angular-locale_en-mu" src="html/lib/angular/i18n/angular-locale_en-mu.js" />
        <File name="angular-locale_en-na" src="html/lib/angular/i18n/angular-locale_en-na.js" />
        <File name="angular-locale_en-nz" src="html/lib/angular/i18n/angular-locale_en-nz.js" />
        <File name="angular-locale_en-ph" src="html/lib/angular/i18n/angular-locale_en-ph.js" />
        <File name="angular-locale_en-pk" src="html/lib/angular/i18n/angular-locale_en-pk.js" />
        <File name="angular-locale_en-pr" src="html/lib/angular/i18n/angular-locale_en-pr.js" />
        <File name="angular-locale_en-pw" src="html/lib/angular/i18n/angular-locale_en-pw.js" />
        <File name="angular-locale_en-sg" src="html/lib/angular/i18n/angular-locale_en-sg.js" />
        <File name="angular-locale_en-tc" src="html/lib/angular/i18n/angular-locale_en-tc.js" />
        <File name="angular-locale_en-tt" src="html/lib/angular/i18n/angular-locale_en-tt.js" />
        <File name="angular-locale_en-um" src="html/lib/angular/i18n/angular-locale_en-um.js" />
        <File name="angular-locale_en-us" src="html/lib/angular/i18n/angular-locale_en-us.js" />
        <File name="angular-locale_en-vg" src="html/lib/angular/i18n/angular-locale_en-vg.js" />
        <File name="angular-locale_en-vi" src="html/lib/angular/i18n/angular-locale_en-vi.js" />
        <File name="angular-locale_en-za" src="html/lib/angular/i18n/angular-locale_en-za.js" />
        <File name="angular-locale_en-zw" src="html/lib/angular/i18n/angular-locale_en-zw.js" />
        <File name="angular-locale_en" src="html/lib/angular/i18n/angular-locale_en.js" />
        <File name="angular-locale_es-419" src="html/lib/angular/i18n/angular-locale_es-419.js" />
        <File name="angular-locale_es-ar" src="html/lib/angular/i18n/angular-locale_es-ar.js" />
        <File name="angular-locale_es-bo" src="html/lib/angular/i18n/angular-locale_es-bo.js" />
        <File name="angular-locale_es-cl" src="html/lib/angular/i18n/angular-locale_es-cl.js" />
        <File name="angular-locale_es-co" src="html/lib/angular/i18n/angular-locale_es-co.js" />
        <File name="angular-locale_es-cr" src="html/lib/angular/i18n/angular-locale_es-cr.js" />
        <File name="angular-locale_es-do" src="html/lib/angular/i18n/angular-locale_es-do.js" />
        <File name="angular-locale_es-ea" src="html/lib/angular/i18n/angular-locale_es-ea.js" />
        <File name="angular-locale_es-ec" src="html/lib/angular/i18n/angular-locale_es-ec.js" />
        <File name="angular-locale_es-es" src="html/lib/angular/i18n/angular-locale_es-es.js" />
        <File name="angular-locale_es-gq" src="html/lib/angular/i18n/angular-locale_es-gq.js" />
        <File name="angular-locale_es-gt" src="html/lib/angular/i18n/angular-locale_es-gt.js" />
        <File name="angular-locale_es-hn" src="html/lib/angular/i18n/angular-locale_es-hn.js" />
        <File name="angular-locale_es-ic" src="html/lib/angular/i18n/angular-locale_es-ic.js" />
        <File name="angular-locale_es-mx" src="html/lib/angular/i18n/angular-locale_es-mx.js" />
        <File name="angular-locale_es-ni" src="html/lib/angular/i18n/angular-locale_es-ni.js" />
        <File name="angular-locale_es-pa" src="html/lib/angular/i18n/angular-locale_es-pa.js" />
        <File name="angular-locale_es-pe" src="html/lib/angular/i18n/angular-locale_es-pe.js" />
        <File name="angular-locale_es-pr" src="html/lib/angular/i18n/angular-locale_es-pr.js" />
        <File name="angular-locale_es-py" src="html/lib/angular/i18n/angular-locale_es-py.js" />
        <File name="angular-locale_es-sv" src="html/lib/angular/i18n/angular-locale_es-sv.js" />
        <File name="angular-locale_es-us" src="html/lib/angular/i18n/angular-locale_es-us.js" />
        <File name="angular-locale_es-uy" src="html/lib/angular/i18n/angular-locale_es-uy.js" />
        <File name="angular-locale_es-ve" src="html/lib/angular/i18n/angular-locale_es-ve.js" />
        <File name="angular-locale_es" src="html/lib/angular/i18n/angular-locale_es.js" />
        <File name="angular-locale_et-ee" src="html/lib/angular/i18n/angular-locale_et-ee.js" />
        <File name="angular-locale_et" src="html/lib/angular/i18n/angular-locale_et.js" />
        <File name="angular-locale_eu-es" src="html/lib/angular/i18n/angular-locale_eu-es.js" />
        <File name="angular-locale_eu" src="html/lib/angular/i18n/angular-locale_eu.js" />
        <File name="angular-locale_fa-af" src="html/lib/angular/i18n/angular-locale_fa-af.js" />
        <File name="angular-locale_fa-ir" src="html/lib/angular/i18n/angular-locale_fa-ir.js" />
        <File name="angular-locale_fa" src="html/lib/angular/i18n/angular-locale_fa.js" />
        <File name="angular-locale_fi-fi" src="html/lib/angular/i18n/angular-locale_fi-fi.js" />
        <File name="angular-locale_fi" src="html/lib/angular/i18n/angular-locale_fi.js" />
        <File name="angular-locale_fil-ph" src="html/lib/angular/i18n/angular-locale_fil-ph.js" />
        <File name="angular-locale_fil" src="html/lib/angular/i18n/angular-locale_fil.js" />
        <File name="angular-locale_fr-be" src="html/lib/angular/i18n/angular-locale_fr-be.js" />
        <File name="angular-locale_fr-bf" src="html/lib/angular/i18n/angular-locale_fr-bf.js" />
        <File name="angular-locale_fr-bi" src="html/lib/angular/i18n/angular-locale_fr-bi.js" />
        <File name="angular-locale_fr-bj" src="html/lib/angular/i18n/angular-locale_fr-bj.js" />
        <File name="angular-locale_fr-bl" src="html/lib/angular/i18n/angular-locale_fr-bl.js" />
        <File name="angular-locale_fr-ca" src="html/lib/angular/i18n/angular-locale_fr-ca.js" />
        <File name="angular-locale_fr-cd" src="html/lib/angular/i18n/angular-locale_fr-cd.js" />
        <File name="angular-locale_fr-cf" src="html/lib/angular/i18n/angular-locale_fr-cf.js" />
        <File name="angular-locale_fr-cg" src="html/lib/angular/i18n/angular-locale_fr-cg.js" />
        <File name="angular-locale_fr-ch" src="html/lib/angular/i18n/angular-locale_fr-ch.js" />
        <File name="angular-locale_fr-ci" src="html/lib/angular/i18n/angular-locale_fr-ci.js" />
        <File name="angular-locale_fr-cm" src="html/lib/angular/i18n/angular-locale_fr-cm.js" />
        <File name="angular-locale_fr-dj" src="html/lib/angular/i18n/angular-locale_fr-dj.js" />
        <File name="angular-locale_fr-fr" src="html/lib/angular/i18n/angular-locale_fr-fr.js" />
        <File name="angular-locale_fr-ga" src="html/lib/angular/i18n/angular-locale_fr-ga.js" />
        <File name="angular-locale_fr-gf" src="html/lib/angular/i18n/angular-locale_fr-gf.js" />
        <File name="angular-locale_fr-gn" src="html/lib/angular/i18n/angular-locale_fr-gn.js" />
        <File name="angular-locale_fr-gp" src="html/lib/angular/i18n/angular-locale_fr-gp.js" />
        <File name="angular-locale_fr-gq" src="html/lib/angular/i18n/angular-locale_fr-gq.js" />
        <File name="angular-locale_fr-km" src="html/lib/angular/i18n/angular-locale_fr-km.js" />
        <File name="angular-locale_fr-lu" src="html/lib/angular/i18n/angular-locale_fr-lu.js" />
        <File name="angular-locale_fr-mc" src="html/lib/angular/i18n/angular-locale_fr-mc.js" />
        <File name="angular-locale_fr-mf" src="html/lib/angular/i18n/angular-locale_fr-mf.js" />
        <File name="angular-locale_fr-mg" src="html/lib/angular/i18n/angular-locale_fr-mg.js" />
        <File name="angular-locale_fr-ml" src="html/lib/angular/i18n/angular-locale_fr-ml.js" />
        <File name="angular-locale_fr-mq" src="html/lib/angular/i18n/angular-locale_fr-mq.js" />
        <File name="angular-locale_fr-ne" src="html/lib/angular/i18n/angular-locale_fr-ne.js" />
        <File name="angular-locale_fr-re" src="html/lib/angular/i18n/angular-locale_fr-re.js" />
        <File name="angular-locale_fr-yt" src="html/lib/angular/i18n/angular-locale_fr-yt.js" />
        <File name="angular-locale_fr" src="html/lib/angular/i18n/angular-locale_fr.js" />
        <File name="angular-locale_gl-es" src="html/lib/angular/i18n/angular-locale_gl-es.js" />
        <File name="angular-locale_gl" src="html/lib/angular/i18n/angular-locale_gl.js" />
        <File name="angular-locale_gsw-ch" src="html/lib/angular/i18n/angular-locale_gsw-ch.js" />
        <File name="angular-locale_gsw" src="html/lib/angular/i18n/angular-locale_gsw.js" />
        <File name="angular-locale_gu-in" src="html/lib/angular/i18n/angular-locale_gu-in.js" />
        <File name="angular-locale_gu" src="html/lib/angular/i18n/angular-locale_gu.js" />
        <File name="angular-locale_he-il" src="html/lib/angular/i18n/angular-locale_he-il.js" />
        <File name="angular-locale_he" src="html/lib/angular/i18n/angular-locale_he.js" />
        <File name="angular-locale_hi-in" src="html/lib/angular/i18n/angular-locale_hi-in.js" />
        <File name="angular-locale_hi" src="html/lib/angular/i18n/angular-locale_hi.js" />
        <File name="angular-locale_hr-hr" src="html/lib/angular/i18n/angular-locale_hr-hr.js" />
        <File name="angular-locale_hr" src="html/lib/angular/i18n/angular-locale_hr.js" />
        <File name="angular-locale_hu-hu" src="html/lib/angular/i18n/angular-locale_hu-hu.js" />
        <File name="angular-locale_hu" src="html/lib/angular/i18n/angular-locale_hu.js" />
        <File name="angular-locale_id-id" src="html/lib/angular/i18n/angular-locale_id-id.js" />
        <File name="angular-locale_id" src="html/lib/angular/i18n/angular-locale_id.js" />
        <File name="angular-locale_in" src="html/lib/angular/i18n/angular-locale_in.js" />
        <File name="angular-locale_is-is" src="html/lib/angular/i18n/angular-locale_is-is.js" />
        <File name="angular-locale_is" src="html/lib/angular/i18n/angular-locale_is.js" />
        <File name="angular-locale_it-it" src="html/lib/angular/i18n/angular-locale_it-it.js" />
        <File name="angular-locale_it-sm" src="html/lib/angular/i18n/angular-locale_it-sm.js" />
        <File name="angular-locale_it" src="html/lib/angular/i18n/angular-locale_it.js" />
        <File name="angular-locale_iw" src="html/lib/angular/i18n/angular-locale_iw.js" />
        <File name="angular-locale_ja-jp" src="html/lib/angular/i18n/angular-locale_ja-jp.js" />
        <File name="angular-locale_ja" src="html/lib/angular/i18n/angular-locale_ja.js" />
        <File name="angular-locale_kn-in" src="html/lib/angular/i18n/angular-locale_kn-in.js" />
        <File name="angular-locale_kn" src="html/lib/angular/i18n/angular-locale_kn.js" />
        <File name="angular-locale_ko-kr" src="html/lib/angular/i18n/angular-locale_ko-kr.js" />
        <File name="angular-locale_ko" src="html/lib/angular/i18n/angular-locale_ko.js" />
        <File name="angular-locale_ln-cd" src="html/lib/angular/i18n/angular-locale_ln-cd.js" />
        <File name="angular-locale_ln" src="html/lib/angular/i18n/angular-locale_ln.js" />
        <File name="angular-locale_lt-lt" src="html/lib/angular/i18n/angular-locale_lt-lt.js" />
        <File name="angular-locale_lt" src="html/lib/angular/i18n/angular-locale_lt.js" />
        <File name="angular-locale_lv-lv" src="html/lib/angular/i18n/angular-locale_lv-lv.js" />
        <File name="angular-locale_lv" src="html/lib/angular/i18n/angular-locale_lv.js" />
        <File name="angular-locale_ml-in" src="html/lib/angular/i18n/angular-locale_ml-in.js" />
        <File name="angular-locale_ml" src="html/lib/angular/i18n/angular-locale_ml.js" />
        <File name="angular-locale_mr-in" src="html/lib/angular/i18n/angular-locale_mr-in.js" />
        <File name="angular-locale_mr" src="html/lib/angular/i18n/angular-locale_mr.js" />
        <File name="angular-locale_ms-my" src="html/lib/angular/i18n/angular-locale_ms-my.js" />
        <File name="angular-locale_ms" src="html/lib/angular/i18n/angular-locale_ms.js" />
        <File name="angular-locale_mt-mt" src="html/lib/angular/i18n/angular-locale_mt-mt.js" />
        <File name="angular-locale_mt" src="html/lib/angular/i18n/angular-locale_mt.js" />
        <File name="angular-locale_nl-cw" src="html/lib/angular/i18n/angular-locale_nl-cw.js" />
        <File name="angular-locale_nl-nl" src="html/lib/angular/i18n/angular-locale_nl-nl.js" />
        <File name="angular-locale_nl-sx" src="html/lib/angular/i18n/angular-locale_nl-sx.js" />
        <File name="angular-locale_nl" src="html/lib/angular/i18n/angular-locale_nl.js" />
        <File name="angular-locale_no" src="html/lib/angular/i18n/angular-locale_no.js" />
        <File name="angular-locale_or-in" src="html/lib/angular/i18n/angular-locale_or-in.js" />
        <File name="angular-locale_or" src="html/lib/angular/i18n/angular-locale_or.js" />
        <File name="angular-locale_pl-pl" src="html/lib/angular/i18n/angular-locale_pl-pl.js" />
        <File name="angular-locale_pl" src="html/lib/angular/i18n/angular-locale_pl.js" />
        <File name="angular-locale_pt-br" src="html/lib/angular/i18n/angular-locale_pt-br.js" />
        <File name="angular-locale_pt-pt" src="html/lib/angular/i18n/angular-locale_pt-pt.js" />
        <File name="angular-locale_pt" src="html/lib/angular/i18n/angular-locale_pt.js" />
        <File name="angular-locale_ro-ro" src="html/lib/angular/i18n/angular-locale_ro-ro.js" />
        <File name="angular-locale_ro" src="html/lib/angular/i18n/angular-locale_ro.js" />
        <File name="angular-locale_ru-ru" src="html/lib/angular/i18n/angular-locale_ru-ru.js" />
        <File name="angular-locale_ru" src="html/lib/angular/i18n/angular-locale_ru.js" />
        <File name="angular-locale_sk-sk" src="html/lib/angular/i18n/angular-locale_sk-sk.js" />
        <File name="angular-locale_sk" src="html/lib/angular/i18n/angular-locale_sk.js" />
        <File name="angular-locale_sl-si" src="html/lib/angular/i18n/angular-locale_sl-si.js" />
        <File name="angular-locale_sl" src="html/lib/angular/i18n/angular-locale_sl.js" />
        <File name="angular-locale_sq-al" src="html/lib/angular/i18n/angular-locale_sq-al.js" />
        <File name="angular-locale_sq" src="html/lib/angular/i18n/angular-locale_sq.js" />
        <File name="angular-locale_sr-cyrl-rs" src="html/lib/angular/i18n/angular-locale_sr-cyrl-rs.js" />
        <File name="angular-locale_sr-latn-rs" src="html/lib/angular/i18n/angular-locale_sr-latn-rs.js" />
        <File name="angular-locale_sr" src="html/lib/angular/i18n/angular-locale_sr.js" />
        <File name="angular-locale_sv-se" src="html/lib/angular/i18n/angular-locale_sv-se.js" />
        <File name="angular-locale_sv" src="html/lib/angular/i18n/angular-locale_sv.js" />
        <File name="angular-locale_sw-tz" src="html/lib/angular/i18n/angular-locale_sw-tz.js" />
        <File name="angular-locale_sw" src="html/lib/angular/i18n/angular-locale_sw.js" />
        <File name="angular-locale_ta-in" src="html/lib/angular/i18n/angular-locale_ta-in.js" />
        <File name="angular-locale_ta" src="html/lib/angular/i18n/angular-locale_ta.js" />
        <File name="angular-locale_te-in" src="html/lib/angular/i18n/angular-locale_te-in.js" />
        <File name="angular-locale_te" src="html/lib/angular/i18n/angular-locale_te.js" />
        <File name="angular-locale_th-th" src="html/lib/angular/i18n/angular-locale_th-th.js" />
        <File name="angular-locale_th" src="html/lib/angular/i18n/angular-locale_th.js" />
        <File name="angular-locale_tl" src="html/lib/angular/i18n/angular-locale_tl.js" />
        <File name="angular-locale_tr-tr" src="html/lib/angular/i18n/angular-locale_tr-tr.js" />
        <File name="angular-locale_tr" src="html/lib/angular/i18n/angular-locale_tr.js" />
        <File name="angular-locale_uk-ua" src="html/lib/angular/i18n/angular-locale_uk-ua.js" />
        <File name="angular-locale_uk" src="html/lib/angular/i18n/angular-locale_uk.js" />
        <File name="angular-locale_ur-pk" src="html/lib/angular/i18n/angular-locale_ur-pk.js" />
        <File name="angular-locale_ur" src="html/lib/angular/i18n/angular-locale_ur.js" />
        <File name="angular-locale_vi-vn" src="html/lib/angular/i18n/angular-locale_vi-vn.js" />
        <File name="angular-locale_vi" src="html/lib/angular/i18n/angular-locale_vi.js" />
        <File name="angular-locale_zh-cn" src="html/lib/angular/i18n/angular-locale_zh-cn.js" />
        <File name="angular-locale_zh-hans-cn" src="html/lib/angular/i18n/angular-locale_zh-hans-cn.js" />
        <File name="angular-locale_zh-hk" src="html/lib/angular/i18n/angular-locale_zh-hk.js" />
        <File name="angular-locale_zh-tw" src="html/lib/angular/i18n/angular-locale_zh-tw.js" />
        <File name="angular-locale_zh" src="html/lib/angular/i18n/angular-locale_zh.js" />
        <File name="angular-locale_zu-za" src="html/lib/angular/i18n/angular-locale_zu-za.js" />
        <File name="angular-locale_zu" src="html/lib/angular/i18n/angular-locale_zu.js" />
        <File name="myview" src="html/partials/myview.html" />
        <File name="translation_en_US" src="translations/translation_en_US.qm" />
        <File name="translation_fr_FR" src="translations/translation_fr_FR.qm" />
        <File name="translation_ja_JP" src="translations/translation_ja_JP.qm" />
        <File name=".translation_de_DE.ts.15784" src="translations/.translation_de_DE.ts.15784.csp" />
        <File name=".translation_en_US.ts.15784" src="translations/.translation_en_US.ts.15784.csp" />
        <File name=".translation_es_ES.ts.15784" src="translations/.translation_es_ES.ts.15784.csp" />
        <File name=".translation_fr_FR.ts.15784" src="translations/.translation_fr_FR.ts.15784.csp" />
        <File name=".translation_ja_JP.ts.15784" src="translations/.translation_ja_JP.ts.15784.csp" />
    </Resources>
    <Topics>
        <Topic name="Emotes_enu" src="Emotes/Emotes_enu.top" topicName="Emotes" language="en_US" />
        <Topic name="Emotes_frf" src="Emotes/Emotes_frf.top" topicName="Emotes" language="fr_FR" />
        <Topic name="Emotes_ged" src="Emotes/Emotes_ged.top" topicName="Emotes" language="de_DE" />
        <Topic name="Emotes_jpj" src="Emotes/Emotes_jpj.top" topicName="Emotes" language="ja_JP" />
        <Topic name="Emotes_spe" src="Emotes/Emotes_spe.top" topicName="Emotes" language="es_ES" />
        <Topic name="Exit_enu" src="Exit/Exit_enu.top" topicName="Exit" language="en_US" />
        <Topic name="Exit_frf" src="Exit/Exit_frf.top" topicName="Exit" language="fr_FR" />
        <Topic name="Exit_ged" src="Exit/Exit_ged.top" topicName="Exit" language="de_DE" />
        <Topic name="Exit_jpj" src="Exit/Exit_jpj.top" topicName="Exit" language="ja_JP" />
        <Topic name="Exit_spe" src="Exit/Exit_spe.top" topicName="Exit" language="es_ES" />
    </Topics>
    <IgnoredPaths />
    <Translations auto-fill="en_US">
        <Translation name="translation_de_DE" src="translations/translation_de_DE.ts" language="de_DE" />
        <Translation name="translation_en_US" src="translations/translation_en_US.ts" language="en_US" />
        <Translation name="translation_es_ES" src="translations/translation_es_ES.ts" language="es_ES" />
        <Translation name="translation_fr_FR" src="translations/translation_fr_FR.ts" language="fr_FR" />
        <Translation name="translation_ja_JP" src="translations/translation_ja_JP.ts" language="ja_JP" />
    </Translations>
</Package>
